<a href="https://colab.research.google.com/github/yogeshkumarrudra/Data_structure/blob/main/DS_lec04(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
# why do we need numpy in python?
# why do we not use list as numpy array in python

import numpy as np
# np is variable we called as alies

In [49]:
#creating array

import numpy as np

a = np.array([1,2,3,4,5,'6'])
# agar vector me koi string aa gaya hai to pura array string ban jyega.
print(a)

['1' '2' '3' '4' '5' '6']


In [50]:
import numpy as np
np_arr = np.array([3,3,3,3.3,'hello', False])
print(bool(np_arr[-1]))
# answer true aayega q ki bool false tabhi answer dayga jab tak bool me 0 ya false ho.
# ya true isliye aaya hai q ki bool me string hai jo ki false ya 0 nhi hai to wo true answer dayga.
# example:-
# l = 'azsdfghjkl';
# print(bool(l))

a = False
print(bool(a))

True
False


In [51]:
import numpy as np

#2-D array
a = np.zeros((5,3))
# print(a)
print(type(a))
print(a.size)
print(a.shape)
print(a.dtype)

# #3-D array
# b= np.zeros((2,3,4), dtype=int)
# print(b)
# print(type(b[0][0][0]))

<class 'numpy.ndarray'>
15
(5, 3)
float64


In [52]:
import numpy as np
a = np.empty((2,3), dtype=int)
print(a)

b = np.full(3,5 , dtype=str)
print(b)

c = np.arange(1,7,2 ,dtype = int)
print(c)



#linspace me end value include rahata hai,  endpoint ko remmove karne ki liye endpoint=false likta hai.
# linspace me start, end, and how many part in which it is divided from start to end.
d = np.linspace(1, 6, 9,)
print(d)



[[          367956923                   0        481036337262]
 [       438086664238        463856468085 5213480087321855834]]
['5' '5' '5']
[1 3 5]
[1.    1.625 2.25  2.875 3.5   4.125 4.75  5.375 6.   ]
