<a href="https://colab.research.google.com/github/yogeshkumarrudra/Data_structure/blob/main/DS_lec04(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
# why do we need numpy in python?
# why do we not use list as numpy array in python

import numpy as np
# np is variable we called as alies

In [49]:
#creating array

import numpy as np

a = np.array([1,2,3,4,5,'6'])
# agar vector me koi string aa gaya hai to pura array string ban jyega.
print(a)

['1' '2' '3' '4' '5' '6']


In [50]:
import numpy as np
np_arr = np.array([3,3,3,3.3,'hello', False])
print(bool(np_arr[-1]))
# answer true aayega q ki bool false tabhi answer dayga jab tak bool me 0 ya false ho.
# ya true isliye aaya hai q ki bool me string hai jo ki false ya 0 nhi hai to wo true answer dayga.
# example:-
# l = 'azsdfghjkl';
# print(bool(l))

a = False
print(bool(a))

True
False


In [51]:
import numpy as np

#2-D array
a = np.zeros((5,3))
# print(a)
print(type(a))
print(a.size)
print(a.shape)
print(a.dtype)

# #3-D array
# b= np.zeros((2,3,4), dtype=int)
# print(b)
# print(type(b[0][0][0]))

<class 'numpy.ndarray'>
15
(5, 3)
float64


In [52]:
import numpy as np
a = np.empty((2,3), dtype=int)
print(a)

b = np.full(3,5 , dtype=str)
print(b)

c = np.arange(1,7,2 ,dtype = int)
print(c)



#linspace me end value include rahata hai,  endpoint ko remmove karne ki liye endpoint=false likta hai.
# linspace me start, end, and how many part in which it is divided from start to end.
d = np.linspace(1, 6, 9,)
print(d)



[[          367956923                   0        481036337262]
 [       438086664238        463856468085 5213480087321855834]]
['5' '5' '5']
[1 3 5]
[1.    1.625 2.25  2.875 3.5   4.125 4.75  5.375 6.   ]


**Broadcasting**

In [76]:
import numpy as np
# a =np.array(1,10,10, dtype = int)
# print(a)
a = np.random.randint(1,7,4)
print (a)
# print(np.random.choice(a))


# b = np.random.choice([2,4,6,9],2)
# print(b)

[5 2 5 1]


In [75]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a*2*b)
print(a+b)
print(b-a)
print(b/a)
print(a/3)



c = [2, 4 , 6,8,9]
print(2*c)

[10 24 42 64 90]
[ 6  8 10 12 14]
[4 4 4 4 4]
[5.         3.         2.33333333 2.         1.8       ]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[2, 4, 6, 8, 9, 2, 4, 6, 8, 9]


In [77]:
import numpy as np
b=np.random.randint(1,7,6)#create a array which have random element in a given range((start,stop),size of a array)
c=np.random.randint(2,7,6)
print(b,c)
print(b*2*c)
print(b+c)
print(b-c)
print(b/c)#operation performs in corrosponding elements

d=np.ones((2,3),dtype=int)
e=np.zeros((2,3),dtype=int)
print(d+e)

[5 3 6 2 5 4] [4 3 3 5 2 4]
[40 18 36 20 20 32]
[9 6 9 7 7 8]
[ 1  0  3 -3  3  0]
[1.25 1.   2.   0.4  2.5  1.  ]
[[1 1 1]
 [1 1 1]]


In [74]:
import numpy as np

a = [1,2,3,4,5]
b = [6,7,8,9,0]
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [78]:
a = np.random.randint(2,15,6)
print(a)

b = a.reshape((3,2))
print(b)

[ 8  5 12  5  7 13]
[[ 8  5]
 [12  5]
 [ 7 13]]


In [108]:
import numpy as np
b=np.random.randint(1,7,6)#create a array which have random element in a given range((start,stop),size of a array)
c=np.random.randint(2,7,6)

t = a.reshape((3,2))
print (t)

u= b.reshape((3,2))
print(u)

# d=np.ones((2,3),dtype=int)
# e=np.zeros((2,3),dtype=int)
# print(d+e)

# x = t.transpose()
# print(x)

# result = np.concatenate((t, u))
# print(result)


print (np.concatenate((t, u),axis =1))
# print(result)

# result  = sum(t,u)
# print(result)



[[ 9 14]
 [ 6 10]
 [12  5]]
[[6 2]
 [1 6]
 [1 2]]
[[ 9 14  6  2]
 [ 6 10  1  6]
 [12  5  1  2]]


In [115]:
import numpy as np
b=np.random.randint(1,7,6)
c=np.random.randint(2,7,6)
print(b,c)
# print(c)

c = np.where(b>4, b,c )
print(c)

[3 3 3 1 6 3] [6 4 2 6 4 3]
[6 4 2 6 6 3]
