<a href="https://colab.research.google.com/github/yogeshkumarrudra/Data_structure/blob/main/lec05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

a = np.random.randint(1,90,25)
# b = np.random.randint(1,90,5)
b = a.reshape((5,5))
print(b)

n = 5
# for i in range(n):
#   print(f"mean of row {i} is {b[i].mean()}")


# col_means = np.mean(b, axis=0)
# print(col_means)

print(f"mean of rows is {b.mean(axis =1)}")
print(f"mean of column is {b.mean(axis =0)}")


b = np.where(b%2==0, -1,b)
print(b)


print("sort according to row wise")
b.sort()
print(b)

print(f"sort according to column {b.sort(axis = 0)}")
print(b)


print("sum of matrix column")
print(b.sum(axis=0))

print("sum of amtrix row wise")
print(b.sum(axis=1))

# sum = 0
# b = np.where(b<=-1, sum =sum+1,b)
# print(b)

count_neg_col = np.sum(np.where(b<0,1,0), axis=0)
print(count_neg_col)

count_neg_row = np.sum(np.where(b<0,1,0), axis =1)
print(count_neg_row)



[[48 13 26 14 26]
 [27 41 53 80 37]
 [62 46 27 63 63]
 [57 76 87 66  9]
 [69 21 18 36 75]]
mean of rows is [25.4 47.6 52.2 59.  43.8]
mean of column is [52.6 39.4 42.2 51.8 42. ]
[[-1 13 -1 -1 -1]
 [27 41 53 -1 37]
 [-1 -1 27 63 63]
 [57 -1 87 -1  9]
 [69 21 -1 -1 75]]
sort according to row wise
[[-1 -1 -1 -1 13]
 [-1 27 37 41 53]
 [-1 -1 27 63 63]
 [-1 -1  9 57 87]
 [-1 -1 21 69 75]]
sort according to column None
[[-1 -1 -1 -1 13]
 [-1 -1  9 41 53]
 [-1 -1 21 57 63]
 [-1 -1 27 63 75]
 [-1 27 37 69 87]]
sum of matrix column
[ -5  23  93 229 291]
sum of amtrix row wise
[  9 101 139 163 219]
[5 4 1 1 0]
[4 2 2 2 1]
