<a href="https://colab.research.google.com/github/yogeshkumarrudra/Data_structure/blob/main/lec05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

a = np.random.randint(1,90,25)
# b = np.random.randint(1,90,5)
b = a.reshape((5,5))
print(b)

n = 5
# for i in range(n):
#   print(f"mean of row {i} is {b[i].mean()}")


# col_means = np.mean(b, axis=0)
# print(col_means)

print(f"mean of rows is {b.mean(axis =1)}")
print(f"mean of column is {b.mean(axis =0)}")


b = np.where(b%2==0, -1,b)
print(b)


print("sort according to row wise")
b.sort()
print(b)

print(f"sort according to column {b.sort(axis = 0)}")
print(b)


print("sum of matrix column")
print(b.sum(axis=0))

print("sum of amtrix row wise")
print(b.sum(axis=1))

# sum = 0
# b = np.where(b<=-1, sum =sum+1,b)
# print(b)

count_neg_col = np.sum(np.where(b<0,1,0), axis=0)
print(count_neg_col)

count_neg_row = np.sum(np.where(b<0,1,0), axis =1)
print(count_neg_row)



[[48 13 26 14 26]
 [27 41 53 80 37]
 [62 46 27 63 63]
 [57 76 87 66  9]
 [69 21 18 36 75]]
mean of rows is [25.4 47.6 52.2 59.  43.8]
mean of column is [52.6 39.4 42.2 51.8 42. ]
[[-1 13 -1 -1 -1]
 [27 41 53 -1 37]
 [-1 -1 27 63 63]
 [57 -1 87 -1  9]
 [69 21 -1 -1 75]]
sort according to row wise
[[-1 -1 -1 -1 13]
 [-1 27 37 41 53]
 [-1 -1 27 63 63]
 [-1 -1  9 57 87]
 [-1 -1 21 69 75]]
sort according to column None
[[-1 -1 -1 -1 13]
 [-1 -1  9 41 53]
 [-1 -1 21 57 63]
 [-1 -1 27 63 75]
 [-1 27 37 69 87]]
sum of matrix column
[ -5  23  93 229 291]
sum of amtrix row wise
[  9 101 139 163 219]
[5 4 1 1 0]
[4 2 2 2 1]


In [53]:
import numpy as np

stock = np.random.randint(20,80,25)
stock = np.reshape(stock,(5,5))
print(stock)

print("\n")

demand = np.random.randint(20,80,25)
demand = np.reshape(demand,(5,5))
print(demand)


print("\n")
# remanning stock

remaning_stock = stock-demand
print(remaning_stock)
print("\n")




print("\n")
print("sum_axis_0\n")
sum_axis_0=np.sum(np.where(remaning_stock<0,-1*remaning_stock,0),axis=0)
print(sum_axis_0)

print("\n")

remaning_stock= np.where(remaning_stock<0, 0,remaning_stock)
print(remaning_stock)


count_zero = np.sum(np.where(remaning_stock==0,1,0))
print(count_zero)

print("\n")
print("sort according to row wise")
remaning_stock.sort()
print(remaning_stock)



[[52 35 35 72 77]
 [24 37 71 70 36]
 [31 47 49 29 24]
 [73 53 61 67 22]
 [34 77 78 68 70]]


[[27 68 29 73 37]
 [77 68 29 35 73]
 [69 44 21 48 48]
 [59 23 75 31 73]
 [59 39 36 28 44]]


[[ 25 -33   6  -1  40]
 [-53 -31  42  35 -37]
 [-38   3  28 -19 -24]
 [ 14  30 -14  36 -51]
 [-25  38  42  40  26]]




sum_axis_0

[116  64  14  20 112]


[[25  0  6  0 40]
 [ 0  0 42 35  0]
 [ 0  3 28  0  0]
 [14 30  0 36  0]
 [ 0 38 42 40 26]]
11


sort according to row wise
[[ 0  0  6 25 40]
 [ 0  0  0 35 42]
 [ 0  0  0  3 28]
 [ 0  0 14 30 36]
 [ 0 26 38 40 42]]
